/**
 * Queries and caches DOM element references for the App Settings tab and related modals.
 */
export function getAppSettingsDOMElements() {
    return {
        currencySelect: document.getElementById('currency-select'),
        languageSelect: document.getElementById('language-select'),
        openGlobalPricingBtn: document.getElementById('open-global-pricing-btn'),
        deviceSyncBtn: document.getElementById('device-sync-btn'),
        deviceSyncModal: document.getElementById('device-sync-modal'),
        closeDeviceSyncModalBtn: document.getElementById('close-device-sync-modal-btn'),
        deviceSyncUserIdDisplay: document.getElementById('device-sync-user-id'),
        deviceSyncCopyBtn: document.getElementById('device-sync-copy-btn'),
        deviceSyncQrContainer: document.getElementById('device-sync-qr-container'),
        deviceSyncInput: document.getElementById('device-sync-input'),
        deviceSyncStatus: document.getElementById('device-sync-status'),
        cancelDeviceSyncBtn: document.getElementById('cancel-device-sync-btn'),
        confirmDeviceSyncBtn: document.getElementById('confirm-device-sync-btn'),
        openDataManagementBtn: document.getElementById('open-data-management-btn'),
        openAccountManagementBtn: document.getElementById('open-account-management-btn'),
        accountDataModal: document.getElementById('account-data-modal'),
        closeAccountDataModalBtn: document.getElementById('close-account-data-modal-btn'),
        closeAccountDataHeaderBtn: document.getElementById('close-account-data-header-btn'),
        accountDataModalTitle: document.getElementById('account-data-modal-title'),
        accountDataSignInTier: document.getElementById('account-data-signin-tier'),
        accountDataDeleteAccountTier: document.getElementById('account-data-delete-account-tier'),
        modalGuestSignInBtn: document.getElementById('modal-guest-signin-btn'),
        accountDataDownloadBtn: document.getElementById('account-data-download-btn'),
        accountDataRestoreBtn: document.getElementById('account-data-restore-btn'),
        accountDataRestoreFileInput: document.getElementById('account-data-restore-file-input'),
        tierClearCacheLabel: document.getElementById('tier-clear-cache-label'),
        tierClearCacheDesc: document.getElementById('tier-clear-cache-desc'),
        modalClearCacheBtn: document.getElementById('modal-clear-cache-btn'),
        modalClearCacheBtnText: document.getElementById('modal-clear-cache-btn-text'),
        tierResetDataLabel: document.getElementById('tier-reset-data-label'),
        tierResetDataDesc: document.getElementById('tier-reset-data-desc'),
        modalResetDataBtn: document.getElementById('modal-reset-data-btn'),
        modalResetDataBtnText: document.getElementById('modal-reset-data-btn-text'),
        modalDeleteAccountBtn: document.getElementById('modal-delete-account-btn'),
        accentColorSwatches: document.querySelectorAll('#settings-tab .accent-swatch'),
        mobileAccentPickerBtn: document.getElementById('mobile-accent-picker-btn'),
        accentPickerModal: document.getElementById('accent-picker-modal'),
        mobileAccentSwatches: document.querySelectorAll('.mobile-accent-swatch'),
        closeAccentPickerBtn: document.getElementById('close-accent-picker-btn'),
        downloadDataModal: document.getElementById('download-data-modal'),
        closeDownloadDataModalBtn: document.getElementById('close-download-data-modal-btn'),
        confirmDownloadDataBtn: document.getElementById('confirm-download-data-btn'),
        cancelDownloadDataBtn: document.getElementById('cancel-download-data-btn'),
        downloadFilenamePreview: document.getElementById('download-filename-preview'),
        globalPricingModal: document.getElementById('global-pricing-modal'),
        closeGlobalPricingModalBtn: document.getElementById('close-global-pricing-modal-btn'),
        globalPricingCurrencySelect: document.getElementById('global-pricing-currency-select'),
        globalPricingGridBody: document.getElementById('global-pricing-grid-body'),
        globalPricingCustomHeader: document.getElementById('global-pricing-custom-header'),
        saveGlobalPricingBtn: document.getElementById('save-global-pricing-btn'),
        resetGlobalPricingBtn: document.getElementById('reset-global-pricing-btn'),
        cancelGlobalPricingBtn: document.getElementById('cancel-global-pricing-btn'),
        cloudSyncToggle: document.getElementById('settings-cloud-sync-toggle'),
        cloudSyncInfo: document.getElementById('settings-cloud-sync-info'),
        addPlayerLink: document.getElementById('settings-add-player-link'),
        deleteModal: document.getElementById('delete-player-modal'),
        deleteTagContainer: document.getElementById('delete-tag-container'),
        deleteTokenContainer: document.getElementById('delete-token-container'),
        deleteTagInput: document.getElementById('delete-player-tag-input'),
        deleteTokenInput: document.getElementById('delete-player-token-input'),
        deleteTagError: document.getElementById('delete-player-tag-error'),
        deleteTokenError: document.getElementById('delete-player-token-error'),
        deleteModalActionsValidate: document.getElementById('delete-modal-actions-validate'),
        deleteModalActionsVerify: document.getElementById('delete-modal-actions-verify'),
        cancelDeletePlayerBtn: document.getElementById('cancel-delete-player-btn'),
        validateDeletePlayerBtn: document.getElementById('validate-delete-player-btn'),
        closeDeletePlayerModalBtn: document.getElementById('close-delete-player-modal-btn'),
        cancelDeleteVerifyBtn: document.getElementById('cancel-delete-verify-btn'),
        verifyDeletePlayerBtn: document.getElementById('verify-delete-player-btn')
    };
}
